print()
name=input("enter your name  ")
print(name)
maths=float(input("enter your mark in maths :"))
science=float(input("enter your mark in science :"))
english=float(input("enter your mark in english :"))
sum=(maths+science+english)
total=("total score of ",name)
print(total,sum)

print()
name1=input(input("enter your name "))
print(name1)
maths=float(input("enter your mark in maths :"))
science=float(input("enter your mark in science :"))
english=float(input("enter your mark in english :"))
sum=(maths+science+english)
total=(" total score of",name1)
print(total,sum)
print()

name2=input(input("enter your name "))
print(name2)
maths=float(input("enter your mark in maths :"))
science=float(input("enter your mark in science :"))
english=float(input("enter your mark in english :"))
sum=(maths+science+english)
total=(" total score is")
print(total,sum)